version: '3.4'

services:
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./default
        target: /etc/nginx/conf.d/default.conf
